language: python

python: "3.7"

git:
  depth: 1

install:
  - pip install -r requirements.txt

script:
  - coverage run -m unittest discover -p "*_test.py"

after_script:
  - bash <(curl -s https://codecov.io/bash)