# Generated by Django 3.1 on 2020-09-14 16:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 15, 16, 52, 51, 160490, tzinfo=utc), verbose_name='ending date'),
            preserve_default=False,
        ),
    ]
