# Generated by Django 3.1 on 2020-10-24 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20201024_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='choice',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='polls.choice'),
        ),
    ]
